import { keyMirror } from '../../utilities/utils'

export const ActionTypes = keyMirror({
    // User and authentication
    SET_CURRENT_USER: null,
    USER_AUTH_STATUS_REQUEST: null,

    USER_SIGNIN_REQUEST: null,
    USER_SIGNIN_SUCCESS: null,
    USER_SIGNIN_FAILURE: null,

    USER_SIGNUP_REQUEST: null,
    USER_SIGNUP_SUCCESS: null,
    USER_SIGNUP_FAILURE: null,

    USER_SIGNOUT_REQUEST: null,
    USER_SIGNOUT_SUCCESS: null,
    USER_SIGNOUT_FAILURE: null,

    USER_DATA_REQUEST: null,
    USER_DATA_SUCCESS: null,
    USER_DATA_FAILURE: null,

    // ACCOUNT
    GET_COMPANY_REQUEST: null,
    GET_COMPANY_SUCCESS: null,
    GET_COMPANY_FAILURE: null,

    UPDATE_ACCOUNT_REQUEST: null,
    UPDATE_ACCOUNT_SUCCESS: null,
    UPDATE_ACCOUNT_FAILURE: null,

    GET_ACCOUNT_USERS_REQUEST: null,
    GET_ACCOUNT_USERS_SUCCESS: null,
    GET_ACCOUNT_USERS_FAILURE: null,

    GET_COMPANY_USERS_REQUEST: null,
    GET_COMPANY_USERS_SUCCESS: null,
    GET_COMPANY_USERS_FAILURE: null,

    GET_ACCOUNT_PREFERENCES_REQUEST: null,
    GET_ACCOUNT_PREFERENCES_SUCCESS: null,
    GET_ACCOUNT_PREFERENCES_FAILURE: null,

    UPDATE_ACCOUNT_PREFERENCE_REQUEST: null,
    UPDATE_ACCOUNT_PREFERENCE_SUCCESS: null,
    UPDATE_ACCOUNT_PREFERENCE_FAILURE: null,

    // Jobs
    GET_JOBS_REQUEST: null,
    GET_JOBS_SUCCESS: null,
    GET_JOBS_FAILURE: null,

    GET_ONE_JOB_REQUEST: null,
    GET_ONE_JOB_SUCCESS: null,
    GET_ONE_JOB_FAILURE: null,

    GET_CLIENT_JOBS_REQUEST: null,
    GET_CLIENT_JOBS_SUCCESS: null,
    GET_CLIENT_JOBS_FAILURE: null,

    CREATE_CLIENT_JOB_REQUEST: null,
    CREATE_CLIENT_JOB_SUCCESS: null,
    CREATE_CLIENT_JOB_FAILURE: null,

    UPDATE_JOB_REQUEST: null,
    UPDATE_JOB_SUCCESS: null,
    UPDATE_JOB_FAILURE: null,

    // Clients
    CREATE_CLIENT_REQUEST: null,
    CREATE_CLIENT_SUCCESS: null,
    CREATE_CLIENT_FAILURE: null,

    GET_CLIENTS_REQUEST: null,
    GET_CLIENTS_SUCCESS: null,
    GET_CLIENTS_FAILURE: null,

    GET_ONE_CLIENT_REQUEST: null,
    GET_ONE_CLIENT_SUCCESS: null,
    GET_ONE_CLIENT_FAILURE: null,

    UPDATE_CLIENT_REQUEST: null,
    UPDATE_CLIENT_SUCCESS: null,
    UPDATE_CLIENT_FAILURE: null,

    // ROOMS
    GET_ROOMS_REQUEST: null,
    GET_ROOMS_SUCCESS: null,
    GET_ROOMS_FAILURE: null,

    GET_ONE_ROOM_REQUEST: null,
    GET_ONE_ROOM_SUCCESS: null,
    GET_ONE_ROOM_FAILURE: null,

    GET_JOB_ROOMS_REQUEST: null,
    GET_JOB_ROOMS_SUCCESS: null,
    GET_JOB_ROOMS_FAILURE: null,

    CREATE_ROOM_REQUEST: null,
    CREATE_ROOM_SUCCESS: null,
    CREATE_ROOM_FAILURE: null,

    UPDATE_ROOM_REQUEST: null,
    UPDATE_ROOM_SUCCESS: null,
    UPDATE_ROOM_FAILURE: null,

    // NOTIFICATIONS
    SEND_NOTIFICATION_REQUEST: null,
    SEND_NOTIFICATION_SUCCESS: null,
    SEND_NOTIFICATION_FAILURE: null,

    // Terms
    CREATE_TERM_REQUEST: null,
    CREATE_TERM_SUCCESS: null,
    CREATE_TERM_FAILURE: null,

    GET_JUST_ONE_TERM_REQUEST: null,
    GET_ONE_TERM_REQUEST: null,
    GET_ONE_TERM_SUCCESS: null,
    GET_ONE_TERM_FAILURE: null,

    GET_DEFAULT_TERMS_REQUEST: null,
    GET_DEFAULT_TERMS_SUCCESS: null,
    GET_DEFAULT_TERMS_FAILURE: null,

    UPDATE_TERM_REQUEST: null,
    UPDATE_TERM_SUCCESS: null,
    UPDATE_TERM_FAILURE: null,

    // Taxes
    CREATE_TAX_REQUEST: null,
    CREATE_TAX_SUCCESS: null,
    CREATE_TAX_FAILURE: null,

    UPDATE_TAX_REQUEST: null,
    UPDATE_TAX_SUCCESS: null,
    UPDATE_TAX_FAILURE: null,

    GET_ONE_TAX_REQUEST: null,
    GET_ONE_TAX_SUCCESS: null,
    GET_ONE_TAX_FAILURE: null,

    // Delivery
    GET_ONE_DELIVERY_REQUEST: null,
    GET_ONE_DELIVERY_SUCCESS: null,
    GET_ONE_DELIVERY_FAILURE: null,

    CREATE_DELIVERY_REQUEST: null,
    CREATE_DELIVERY_SUCCESS: null,
    CREATE_DELIVERY_FAILURE: null,

    UPDATE_DELIVERY_REQUEST: null,
    UPDATE_DELIVERY_SUCCESS: null,
    UPDATE_DELIVERY_FAILURE: null,

    // Markup
    GET_ONE_MARKUP_REQUEST: null,
    GET_ONE_MARKUP_SUCCESS: null,
    GET_ONE_MARKUP_FAILURE: null,

    CREATE_MARKUP_REQUEST: null,
    CREATE_MARKUP_SUCCESS: null,
    CREATE_MARKUP_FAILURE: null,

    GET_DEFAULT_MARKUPS_REQUEST: null,
    GET_DEFAULT_MARKUPS_SUCCESS: null,
    GET_DEFAULT_MARKUPS_FAILURE: null,

    GET_ONE_MARKUP_BY_ID_REQUEST: null,
    GET_ONE_MARKUP_BY_ID_SUCCESS: null,
    GET_ONE_MARKUP_BY_ID_FAILURE: null,

    UPDATE_MARKUP_REQUEST: null,
    UPDATE_MARKUP_SUCCESS: null,
    UPDATE_MARKUP_FAILURE: null,

    // CABINET
    GET_ONE_CABINET_REQUEST: null,
    GET_ONE_CABINET_SUCCESS: null,
    GET_ONE_CABINET_FAILURE: null,

    GET_CABINETS_REQUEST: null,
    GET_CABINETS_SUCCESS: null,
    GET_CABINETS_FAILURE: null,

    GET_SETUP_CABINETS_REQUEST: null,
    GET_SETUP_CABINETS_SUCCESS: null,
    GET_SETUP_CABINETS_FAILURE: null,

    CREATE_CABINET_REQUEST: null,
    CREATE_CABINET_SUCCESS: null,
    CREATE_CABINET_FAILURE: null,

    UPDATE_CABINET_REQUEST: null,
    UPDATE_CABINET_SUCCESS: null,
    UPDATE_CABINET_FAILURE: null,

    GET_ONE_CABINET_SPECIFICATION_REQUEST: null,
    GET_ONE_CABINET_SPECIFICATION_SUCCESS: null,
    GET_ONE_CABINET_SPECIFICATION_FAILURE: null,

    UPDATE_CABINET_SPECIFICATION_REQUEST: null,
    UPDATE_CABINET_SPECIFICATION_SUCCESS: null,
    UPDATE_CABINET_SPECIFICATION_FAILURE: null,

    CREATE_CABINET_SPECIFICATION_REQUEST: null,
    CREATE_CABINET_SPECIFICATION_SUCCESS: null,
    CREATE_CABINET_SPECIFICATION_FAILURE: null,

    GET_ONE_CABINET_BY_ID_REQUEST: null,
    GET_ONE_CABINET_BY_ID_SUCCESS: null,
    GET_ONE_CABINET_BY_ID_FAILURE: null,

    // PANELS
    GET_ONE_PANEL_REQUEST: null,
    GET_ONE_PANEL_SUCCESS: null,
    GET_ONE_PANEL_FAILURE: null,

    GET_ROOM_PANELS_REQUEST: null,
    GET_ROOM_PANELS_SUCCESS: null,
    GET_ROOM_PANELS_FAILURE: null,

    GET_SETUP_PANELS_REQUEST: null,
    GET_SETUP_PANELS_SUCCESS: null,
    GET_SETUP_PANELS_FAILURE: null,

    CREATE_PANEL_REQUEST: null,
    CREATE_PANEL_SUCCESS: null,
    CREATE_PANEL_FAILURE: null,

    // MATERIALS
    GET_DEFAULT_MATERIALS_REQUEST: null,
    GET_DEFAULT_MATERIALS_SUCCESS: null,
    GET_DEFAULT_MATERIALS_FAILURE: null,

    GET_SETUP_MATERIALS_REQUEST: null,
    GET_SETUP_MATERIALS_SUCCESS: null,
    GET_SETUP_MATERIALS_FAILURE: null,

    GET_ONE_MATERIAL_REQUEST: null,
    GET_ONE_MATERIAL_SUCCESS: null,
    GET_ONE_MATERIAL_FAILURE: null,

    UPDATE_DEFAULT_MATERIAL_REQUEST: null,
    UPDATE_DEFAULT_MATERIAL_SUCCESS: null,
    UPDATE_DEFAULT_MATERIAL_FAILURE: null,

    GET_DEFAULT_MATERIALS_NAMES_REQUEST: null,
    GET_DEFAULT_MATERIALS_NAMES_SUCCESS: null,
    GET_DEFAULT_MATERIALS_NAMES_FAILURE: null,

    GET_SETUP_MATERIALS_NAMES_REQUEST: null,
    GET_SETUP_MATERIALS_NAMES_SUCCESS: null,
    GET_SETUP_MATERIALS_NAMES_FAILURE: null,

    GET_ROOM_MATERIAL_REQUEST: null,
    GET_ROOM_MATERIAL_SUCCESS: null,
    GET_ROOM_MATERIAL_FAILURE: null,

    CREATE_ROOM_MATERIAL_REQUEST: null,
    CREATE_ROOM_MATERIAL_SUCCESS: null,
    CREATE_ROOM_MATERIAL_FAILURE: null,

    UPDATE_ROOM_MATERIAL_REQUEST: null,
    UPDATE_ROOM_MATERIAL_SUCCESS: null,
    UPDATE_ROOM_MATERIAL_FAILURE: null,

    // HARDWARES
    GET_DEFAULT_HARDWARES_REQUEST: null,
    GET_DEFAULT_HARDWARES_SUCCESS: null,
    GET_DEFAULT_HARDWARES_FAILURE: null,

    GET_ONE_HARDWARE_REQUEST: null,
    GET_ONE_HARDWARE_SUCCESS: null,
    GET_ONE_HARDWARE_FAILURE: null,

    CREATE_HARDWARE_REQUEST: null,
    CREATE_HARDWARE_SUCCESS: null,
    CREATE_HARDWARE_FAILURE: null,

    UPDATE_HARDWARE_REQUEST: null,
    UPDATE_HARDWARE_SUCCESS: null,
    UPDATE_HARDWARE_FAILURE: null,

    // LETTERS
    GET_DEFAULT_LETTERS_REQUEST: null,
    GET_DEFAULT_LETTERS_SUCCESS: null,
    GET_DEFAULT_LETTERS_FAILURE: null,

    GET_ONE_LETTER_REQUEST: null,
    GET_ONE_LETTER_SUCCESS: null,
    GET_ONE_LETTER_FAILURE: null,

    UPDATE_LETTER_REQUEST: null,
    UPDATE_LETTER_SUCCESS: null,
    UPDATE_LETTER_FAILURE: null,

    // DOORS
    GET_DOORS_REQUEST: null,
    GET_DOORS_SUCCESS: null,
    GET_DOORS_FAILURE: null,

    GET_DOOR_PROFILES_REQUEST: null,
    GET_DOOR_PROFILES_SUCCESS: null,
    GET_DOOR_PROFILES_FAILURE: null,

    // ACCESSORIES
    GET_ACCESSORIES_REQUEST: null,
    GET_ACCESSORIES_SUCCESS: null,
    GET_ACCESSORIES_FAILURE: null,

    GET_ROOM_ACCESSORIES_REQUEST: null,
    GET_ROOM_ACCESSORIES_SUCCESS: null,
    GET_ROOM_ACCESSORIES_FAILURE: null,

    GET_SETUP_HARDWARES_REQUEST: null,
    GET_SETUP_HARDWARES_SUCCESS: null,
    GET_SETUP_HARDWARES_FAILURE: null,

    GET_DEFAULT_ACCESSORIES_REQUEST: null,
    GET_DEFAULT_ACCESSORIES_SUCCESS: null,
    GET_DEFAULT_ACCESSORIES_FAILURE: null,

    CREATE_ROOM_ACCESSORY_REQUEST: null,
    CREATE_ROOM_ACCESSORY_SUCCESS: null,
    CREATE_ROOM_ACCESSORY_FAILURE: null,

    // TRIMS
    GET_TRIMS_REQUEST: null,
    GET_TRIMS_SUCCESS: null,
    GET_TRIMS_FAILURE: null,

    GET_DEFAULT_TRIMS_REQUEST: null,
    GET_DEFAULT_TRIMS_SUCCESS: null,
    GET_DEFAULT_TRIMS_FAILURE: null,

    GET_ONE_TRIM_MOLDING_REQUEST: null,
    GET_ONE_TRIM_MOLDING_SUCCESS: null,
    GET_ONE_TRIM_MOLDING_FAILURE: null,

    GET_TRIM_MOLDING_CLASSIFICATIONS_REQUEST: null,
    GET_TRIM_MOLDING_CLASSIFICATIONS_SUCCESS: null,
    GET_TRIM_MOLDING_CLASSIFICATIONS_FAILURE: null,

    GET_TRIM_MOLDING_SUBCLASSIFICATIONS_REQUEST: null,
    GET_TRIM_MOLDING_SUBCLASSIFICATIONS_SUCCESS: null,
    GET_TRIM_MOLDING_SUBCLASSIFICATIONS_FAILURE: null,

    UPDATE_TRIM_MOLDING_REQUEST: null,
    UPDATE_TRIM_MOLDING_SUCCESS: null,
    UPDATE_TRIM_MOLDING_FAILURE: null,

    CREATE_TRIM_MOLDING_REQUEST: null,
    CREATE_TRIM_MOLDING_SUCCESS: null,
    CREATE_TRIM_MOLDING_FAILURE: null,

    GET_ROOM_TRIM_MOLDINGS_REQUEST: null,
    GET_ROOM_TRIM_MOLDINGS_SUCCESS: null,
    GET_ROOM_TRIM_MOLDINGS_FAILURE: null,

    // FINISHES
    GET_SETUP_FINISHES_REQUEST: null,
    GET_SETUP_FINISHES_SUCCESS: null,
    GET_SETUP_FINISHES_FAILURE: null,

    UPDATE_SETUP_FINISHES_REQUEST: null,
    UPDATE_SETUP_FINISHES_SUCCESS: null,
    UPDATE_SETUP_FINISHES_FAILURE: null,

    // PROFILES
    GET_PROFILE_PANELS_REQUEST: null,
    GET_PROFILE_PANELS_SUCCESS: null,
    GET_PROFILE_PANELS_FAILURE: null,

    GET_PROFILE_EDGES_REQUEST: null,
    GET_PROFILE_EDGES_SUCCESS: null,
    GET_PROFILE_EDGES_FAILURE: null,

    GET_PROFILE_FRAMES_REQUEST: null,
    GET_PROFILE_FRAMES_SUCCESS: null,
    GET_PROFILE_FRAMES_FAILURE: null,
})
