version: "3.6"
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5932:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: ${DB_NAME}
volumes:
  db:
    driver: local
