import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1676040517695 implements MigrationInterface {
    name = 'Initial1676040517695'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "hardware_set" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "account_id" integer, CONSTRAINT "PK_bfea111079ef7a62458af4aa21f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "address" ("id" SERIAL NOT NULL, "type" text NOT NULL, "phone_numbers" text NOT NULL, "account_id" integer, "name_salutation" text, "name_first" text, "name_last" text, "name_title" text, CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cabinet_specifications" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "dimensions_height" real NOT NULL, "dimensions_elevation" real NOT NULL DEFAULT '0', "dimensions_depth" real NOT NULL, "dimensions_toe_kick_height" real NOT NULL DEFAULT '4.25', "part_counts_sides" integer NOT NULL, "part_counts_trays" integer NOT NULL, "part_counts_doors" integer NOT NULL, "part_counts_drawers" integer NOT NULL, "part_counts_drawer_fronts" integer NOT NULL, "intrinsic_top_included" boolean NOT NULL DEFAULT true, "intrinsic_top_finished_sides_count" integer NOT NULL DEFAULT '2', "intrinsic_top_depth_difference" real NOT NULL DEFAULT '0', "intrinsic_back_included" boolean NOT NULL DEFAULT true, "intrinsic_back_position" text NOT NULL DEFAULT 'behind', "intrinsic_back_finished_sides_count" integer NOT NULL DEFAULT '2', "intrinsic_deck_included" boolean NOT NULL DEFAULT true, "intrinsic_deck_finished_sides_count" integer NOT NULL DEFAULT '2', "intrinsic_deck_depth_difference" real NOT NULL DEFAULT '0', "intrinsic_shelves_adjustable_quantity" integer NOT NULL DEFAULT '0', "intrinsic_shelves_adjustable_finished_sides_count" integer NOT NULL DEFAULT '2', "intrinsic_shelves_adjustable_depth_difference" real NOT NULL DEFAULT '0', "intrinsic_shelves_fixed_quantity" integer NOT NULL DEFAULT '0', "intrinsic_shelves_fixed_finished_sides_count" integer NOT NULL DEFAULT '2', "intrinsic_shelves_fixed_depth_difference" real NOT NULL DEFAULT '0', "intrinsic_nailer_height" real NOT NULL DEFAULT '0', "intrinsic_nailer_quantity" integer NOT NULL DEFAULT '1', "intrinsic_nailer_finished_sides_count" integer NOT NULL DEFAULT '2', "intrinsic_nailer_subtract_nailer_from_back" boolean NOT NULL DEFAULT false, "intrinsic_sides_finished_sides_count" integer NOT NULL DEFAULT '2', "intrinsic_sides_depth_difference" real NOT NULL DEFAULT '0', "intrinsic_stretchers_back_depth" real NOT NULL DEFAULT '0', "intrinsic_stretchers_back_finished_sides_count" integer NOT NULL DEFAULT '0', "intrinsic_stretchers_top_depth" real NOT NULL DEFAULT '0', "intrinsic_stretchers_top_finished_sides_count" integer NOT NULL DEFAULT '0', "intrinsic_stretchers_bottom_depth" real NOT NULL DEFAULT '0', "intrinsic_stretchers_bottom_finished_sides_count" integer NOT NULL DEFAULT '0', "intrinsic_face_frame_rail_height" real NOT NULL DEFAULT '3', "intrinsic_face_frame_rail_finished_sides" integer NOT NULL DEFAULT '2', "intrinsic_face_frame_stile_width" real NOT NULL DEFAULT '1.5', "intrinsic_face_frame_stile_finished_sides" integer NOT NULL DEFAULT '2', "intrinsic_filler_width" real NOT NULL DEFAULT '0', "intrinsic_drawers_allowance" real NOT NULL DEFAULT '0', "intrinsic_drawers_depth_difference" real NOT NULL DEFAULT '0', CONSTRAINT "PK_a23f521046585b5ee033fb4f5c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "markup" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "description" text, "account_id" integer, "fees_design" real NOT NULL, "fees_show_design_on_estimate" boolean NOT NULL DEFAULT false, "fees_sales_commission" real NOT NULL, "fees_profit" real NOT NULL, "fees_overhead" real NOT NULL, "fees_additional" real NOT NULL DEFAULT '0', "fees_fixed" real NOT NULL DEFAULT '0', "taxes_sales_tax" real NOT NULL, "taxes_show_on_reports" boolean NOT NULL DEFAULT false, "taxes_applied_to_materials" boolean NOT NULL DEFAULT true, "taxes_applied_to_shop_labor" boolean NOT NULL DEFAULT false, "taxes_applied_to_installation" boolean NOT NULL DEFAULT false, "taxes_applied_to_delivery" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_538ba7ba13a4674c798e546b9a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "finish" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "type" text NOT NULL, "description" text NOT NULL, "discount" real, "account_id" integer, "price_per_part_two_sides_cost" real, "price_per_part_simple_percent" integer NOT NULL DEFAULT '100', "price_per_square_feet_two_sides_cost" real, "price_per_square_feet_simple_percent" integer NOT NULL DEFAULT '67', "price_per_square_feet_in_house_cost" real, CONSTRAINT "PK_6236f6fb29d64c850790581fe61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "vendor" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "account_id" integer, CONSTRAINT "PK_931a23f6231a57604f5a0e32780" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "material_type" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, CONSTRAINT "PK_5a4135c8b2d9e33f55b25e78e21" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "model" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "material_type_id" integer, CONSTRAINT "PK_d6df271bba301d5cc79462912a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "material" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "purpose" text NOT NULL, "source" text NOT NULL, "name" text NOT NULL, "description" text NOT NULL, "price" real NOT NULL, "discount" real NOT NULL DEFAULT '0', "waste_factor" real NOT NULL DEFAULT '0', "is_finished" boolean NOT NULL DEFAULT false, "type_id" integer, "vendor_id" integer, "account_id" integer, CONSTRAINT "PK_0343d0d577f3effc2054cbaca7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "profile" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "type" text NOT NULL, "upcharge" real, "image_url" text, "vendor_id" integer, "account_id" integer, "room_id" integer, CONSTRAINT "PK_3dd8bfc97e4a77c70971591bdcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "material_set" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "account_id" integer, "exterior_openings_door_model_id" integer, "exterior_openings_door_material_id" integer, "exterior_openings_door_profile_set_edge_id" integer, "exterior_openings_door_profile_set_frame_id" integer, "exterior_openings_door_profile_set_panel_id" integer, "exterior_openings_door_finish_set_process_id" integer, "exterior_openings_door_finish_set_glaze_id" integer, "exterior_openings_door_finish_set_paint_id" integer, "exterior_openings_drawer_model_id" integer, "exterior_openings_drawer_material_id" integer, "exterior_openings_drawer_profile_set_edge_id" integer, "exterior_openings_drawer_profile_set_frame_id" integer, "exterior_openings_drawer_profile_set_panel_id" integer, "exterior_openings_drawer_finish_set_process_id" integer, "exterior_openings_drawer_finish_set_glaze_id" integer, "exterior_openings_drawer_finish_set_paint_id" integer, "exterior_panels_appliance_model_id" integer, "exterior_panels_appliance_material_id" integer, "exterior_panels_appliance_profile_set_edge_id" integer, "exterior_panels_appliance_profile_set_frame_id" integer, "exterior_panels_appliance_profile_set_panel_id" integer, "exterior_panels_appliance_finish_set_process_id" integer, "exterior_panels_appliance_finish_set_glaze_id" integer, "exterior_panels_appliance_finish_set_paint_id" integer, "exterior_panels_end_model_id" integer, "exterior_panels_end_material_id" integer, "exterior_panels_end_profile_set_edge_id" integer, "exterior_panels_end_profile_set_frame_id" integer, "exterior_panels_end_profile_set_panel_id" integer, "exterior_panels_end_finish_set_process_id" integer, "exterior_panels_end_finish_set_glaze_id" integer, "exterior_panels_end_finish_set_paint_id" integer, "exterior_panels_wainscot_model_id" integer, "exterior_panels_wainscot_material_id" integer, "exterior_panels_wainscot_profile_set_edge_id" integer, "exterior_panels_wainscot_profile_set_frame_id" integer, "exterior_panels_wainscot_profile_set_panel_id" integer, "exterior_panels_wainscot_finish_set_process_id" integer, "exterior_panels_wainscot_finish_set_glaze_id" integer, "exterior_panels_wainscot_finish_set_paint_id" integer, "exterior_panels_slab_model_id" integer, "exterior_panels_slab_material_id" integer, "exterior_panels_slab_profile_set_edge_id" integer, "exterior_panels_slab_profile_set_frame_id" integer, "exterior_panels_slab_profile_set_panel_id" integer, "exterior_panels_slab_finish_set_process_id" integer, "exterior_panels_slab_finish_set_glaze_id" integer, "exterior_panels_slab_finish_set_paint_id" integer, "exterior_fillers_model_id" integer, "exterior_fillers_material_id" integer, "exterior_fillers_profile_set_edge_id" integer, "exterior_fillers_profile_set_frame_id" integer, "exterior_fillers_profile_set_panel_id" integer, "exterior_fillers_finish_set_process_id" integer, "exterior_fillers_finish_set_glaze_id" integer, "exterior_fillers_finish_set_paint_id" integer, "exterior_toes_model_id" integer, "exterior_toes_material_id" integer, "exterior_toes_profile_set_edge_id" integer, "exterior_toes_profile_set_frame_id" integer, "exterior_toes_profile_set_panel_id" integer, "exterior_toes_finish_set_process_id" integer, "exterior_toes_finish_set_glaze_id" integer, "exterior_toes_finish_set_paint_id" integer, "exterior_face_frame_model_id" integer, "exterior_face_frame_material_id" integer, "exterior_face_frame_profile_set_edge_id" integer, "exterior_face_frame_profile_set_frame_id" integer, "exterior_face_frame_profile_set_panel_id" integer, "exterior_face_frame_finish_set_process_id" integer, "exterior_face_frame_finish_set_glaze_id" integer, "exterior_face_frame_finish_set_paint_id" integer, "exterior_edgebanding_model_id" integer, "exterior_edgebanding_material_id" integer, "exterior_edgebanding_profile_set_edge_id" integer, "exterior_edgebanding_profile_set_frame_id" integer, "exterior_edgebanding_profile_set_panel_id" integer, "exterior_edgebanding_finish_set_process_id" integer, "exterior_edgebanding_finish_set_glaze_id" integer, "exterior_edgebanding_finish_set_paint_id" integer, "exterior_molding_crown_model_id" integer, "exterior_molding_crown_material_id" integer, "exterior_molding_crown_profile_set_edge_id" integer, "exterior_molding_crown_profile_set_frame_id" integer, "exterior_molding_crown_profile_set_panel_id" integer, "exterior_molding_crown_finish_set_process_id" integer, "exterior_molding_crown_finish_set_glaze_id" integer, "exterior_molding_crown_finish_set_paint_id" integer, "exterior_molding_light_rail_model_id" integer, "exterior_molding_light_rail_material_id" integer, "exterior_molding_light_rail_profile_set_edge_id" integer, "exterior_molding_light_rail_profile_set_frame_id" integer, "exterior_molding_light_rail_profile_set_panel_id" integer, "exterior_molding_light_rail_finish_set_process_id" integer, "exterior_molding_light_rail_finish_set_glaze_id" integer, "exterior_molding_light_rail_finish_set_paint_id" integer, "interior_cabinets_unfinished_interior_id" integer, "interior_cabinets_unfinished_back_id" integer, "interior_cabinets_unfinished_finish_set_process_id" integer, "interior_cabinets_unfinished_finish_set_glaze_id" integer, "interior_cabinets_unfinished_finish_set_paint_id" integer, "interior_cabinets_finished_interior_id" integer, "interior_cabinets_finished_back_id" integer, "interior_cabinets_finished_finish_set_process_id" integer, "interior_cabinets_finished_finish_set_glaze_id" integer, "interior_cabinets_finished_finish_set_paint_id" integer, "interior_openings_box_model_id" integer, "interior_openings_box_material_id" integer, "interior_openings_box_profile_set_edge_id" integer, "interior_openings_box_profile_set_frame_id" integer, "interior_openings_box_profile_set_panel_id" integer, "interior_openings_box_finish_set_process_id" integer, "interior_openings_box_finish_set_glaze_id" integer, "interior_openings_box_finish_set_paint_id" integer, "interior_openings_tray_model_id" integer, "interior_openings_tray_material_id" integer, "interior_openings_tray_profile_set_edge_id" integer, "interior_openings_tray_profile_set_frame_id" integer, "interior_openings_tray_profile_set_panel_id" integer, "interior_openings_tray_finish_set_process_id" integer, "interior_openings_tray_finish_set_glaze_id" integer, "interior_openings_tray_finish_set_paint_id" integer, CONSTRAINT "PK_bf795de17b459a2cc96e527e1f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "terms" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" text NOT NULL, "name" text NOT NULL, "description" text, "delivered" boolean NOT NULL DEFAULT true, "installed" boolean NOT NULL DEFAULT true, "payments" jsonb, "payment_due" integer, "discount_due" integer, "discount_percent" integer, "adjust_total" boolean NOT NULL DEFAULT false, "text" text, "account_id" integer, "conditions_proposal" text, "conditions_estimate" text, CONSTRAINT "PK_33b6fe77d6ace7ff43cc8a65958" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "account_preferences" ("id" SERIAL NOT NULL, "report_text" text, "suspend" boolean NOT NULL DEFAULT false, "rate_per_minute" real, "terms_id" integer, "markup_id" integer, "material_set_id" integer, "hardware_set_id" integer, "cabinet_specifications_id" integer, CONSTRAINT "PK_35f5ce85c1ef8f032df1311b452" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "client_preferences" ("id" SERIAL NOT NULL, "report_text" text, "suspend" boolean NOT NULL DEFAULT false, "terms_id" integer, "markup_id" integer, "material_set_id" integer, "hardware_set_id" integer, "cabinet_specifications_id" integer, CONSTRAINT "PK_0d06e691326d586481f28447cfb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "job_preferences" ("id" SERIAL NOT NULL, "report_text" text, "suspend" boolean NOT NULL DEFAULT false, "terms_id" integer, "markup_id" integer, "material_set_id" integer, "hardware_set_id" integer, "cabinet_specifications_id" integer, "delivery_text" text, "delivery_trip_quantity" integer, "delivery_miles_to_job_site" integer, "delivery_per_trip" real, "delivery_per_mile" real, "delivery_per_box" real, CONSTRAINT "PK_0fec48157a95b4d070dd1527244" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "client" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "email" text, "account_id" integer, "preferences_id" integer, "addresses_mailing_id" integer, "addresses_physical_id" integer, CONSTRAINT "REL_0d06e691326d586481f28447cf" UNIQUE ("preferences_id"), CONSTRAINT "REL_0b35eeade60c594a9b0b2a61b7" UNIQUE ("addresses_mailing_id"), CONSTRAINT "REL_487d70af2ae8a1d665b3c16c1b" UNIQUE ("addresses_physical_id"), CONSTRAINT "PK_96da49381769303a6515a8785c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "job" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "estimate_date" TIMESTAMP NOT NULL DEFAULT now(), "proposal_date" TIMESTAMP NOT NULL DEFAULT now(), "description" text, "subdivision" text, "lot_number" integer, "client_id" integer NOT NULL, "account_id" integer NOT NULL, "status" text NOT NULL DEFAULT 'estimate', "preferences_id" integer, "notes_internal" text, "notes_external" text, CONSTRAINT "REL_0fec48157a95b4d070dd152724" UNIQUE ("preferences_id"), CONSTRAINT "PK_98ab1c14ff8d1cf80d18703b92f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "upcharge" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "description" text, "time" integer, "amount" real NOT NULL, "report" boolean NOT NULL DEFAULT true, "account_id" integer NOT NULL, CONSTRAINT "PK_aafc28551da1156a8575ac79e22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "room" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "total_price" real NOT NULL DEFAULT '0', "name" text NOT NULL, "elevation" text, "status" text NOT NULL DEFAULT 'estimate', "material_set_id" integer NOT NULL, "hardware_set_id" integer NOT NULL, "job_id" integer NOT NULL, "account_id" integer NOT NULL, CONSTRAINT "REL_12dd210e46c2e7082542370659" UNIQUE ("material_set_id"), CONSTRAINT "REL_5413f589e26d684ee473be324b" UNIQUE ("hardware_set_id"), CONSTRAINT "PK_c6d46db005d623e691b2fbcba23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "toe_platform" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "depth" real NOT NULL DEFAULT '18', "height" real NOT NULL DEFAULT '0', "ends_count" integer NOT NULL DEFAULT '2', "sleepers_count" integer NOT NULL, "min_length" real NOT NULL DEFAULT '0', "max_length" real NOT NULL DEFAULT '0', "cabinet_id" integer, "account_id" integer, "room_id" integer, CONSTRAINT "PK_bf8f154f63ebaa09eea5ebe29a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "panel" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "depth" real NOT NULL DEFAULT '18', "height" real NOT NULL DEFAULT '0', "type" text NOT NULL, "width" real NOT NULL DEFAULT '0', "panels_count" integer, "cabinet_id" integer, "account_id" integer, "room_id" integer, CONSTRAINT "PK_bbd5674b69f7448974aa41ab347" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "filler" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "depth" real NOT NULL DEFAULT '18', "height" real NOT NULL DEFAULT '0', "cabinet_id" integer, "account_id" integer, "room_id" integer, CONSTRAINT "PK_9853d92975791b2161c09774a72" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "opening" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text, "description" text, "type" text NOT NULL, "price" real NOT NULL, "discount" real NOT NULL DEFAULT '0', "image_url" text, "model_id" integer, "vendor_id" integer, "account_id" integer, "room_id" integer, "cabinet_id" integer, CONSTRAINT "REL_2ab91dcc4c611b02f51dc9d953" UNIQUE ("model_id"), CONSTRAINT "PK_8b433fbb5ac3bc1cda8afc64fa2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cabinet" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "type" text NOT NULL, "name" text NOT NULL, "corner_placement" text, "base_type" text NOT NULL DEFAULT 'standard', "is_interior_finished" boolean NOT NULL, "is_framed" boolean NOT NULL, "favourite" boolean NOT NULL DEFAULT false, "cornered" boolean NOT NULL DEFAULT false, "specifications_id" integer NOT NULL, "room_id" integer, "account_id" integer NOT NULL, CONSTRAINT "REL_a23f521046585b5ee033fb4f5c" UNIQUE ("specifications_id"), CONSTRAINT "PK_6e1aaa59022d432d8cf3df7ef46" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "account" ("id" SERIAL NOT NULL, "name" text NOT NULL, "email" text NOT NULL, "password" text, "salt" text, "role" text NOT NULL DEFAULT 'sales', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "preferences_id" integer, "stripe_key" text, "company_name" text NOT NULL, "company_contact_name" text, "company_logo" text, CONSTRAINT "UQ_4c8f96ccf523e9a3faefd5bdd4c" UNIQUE ("email"), CONSTRAINT "REL_35f5ce85c1ef8f032df1311b45" UNIQUE ("preferences_id"), CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cabinet_equipment" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "category" text NOT NULL, "classification" text NOT NULL, "name" text NOT NULL, "description" text, "discount" real, "price" real NOT NULL DEFAULT '0', "measurement" text NOT NULL DEFAULT 'unit', "report" boolean NOT NULL DEFAULT true, "waste_factor" real NOT NULL DEFAULT '0', "finish_complexity" text NOT NULL DEFAULT 'none', "cabinet_id" integer, "room_id" integer, "account_id" integer NOT NULL, CONSTRAINT "PK_901a5f021fe0d5e847b3cf42209" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "letter" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, "description" text NOT NULL, "body" text NOT NULL, "account_id" integer, CONSTRAINT "PK_7a85cf0e444dff7c656a31b32bf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "room_upcharges_upcharge" ("room_id" integer NOT NULL, "upcharge_id" integer NOT NULL, CONSTRAINT "PK_222bbf969da65a573d5229e32a6" PRIMARY KEY ("room_id", "upcharge_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_99706143f4e3444e570910a651" ON "room_upcharges_upcharge" ("room_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a614a4aab6d53ba2025766ab9" ON "room_upcharges_upcharge" ("upcharge_id") `);
        await queryRunner.query(`CREATE TABLE "cabinet_upcharges_upcharge" ("cabinet_id" integer NOT NULL, "upcharge_id" integer NOT NULL, CONSTRAINT "PK_d8d3cb111e0157f97e32b20dd8a" PRIMARY KEY ("cabinet_id", "upcharge_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_de9c5d240a47f96f784647580b" ON "cabinet_upcharges_upcharge" ("cabinet_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6a90bec44895e1441d3343e83" ON "cabinet_upcharges_upcharge" ("upcharge_id") `);
        await queryRunner.query(`CREATE TABLE "cabinet_equipment_upcharges_upcharge" ("cabinet_equipment_id" integer NOT NULL, "upcharge_id" integer NOT NULL, CONSTRAINT "PK_71aca354397e5657f229605800b" PRIMARY KEY ("cabinet_equipment_id", "upcharge_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87f2db6158854538d56ac1218b" ON "cabinet_equipment_upcharges_upcharge" ("cabinet_equipment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_12baf7572789a196ce6fa88dbc" ON "cabinet_equipment_upcharges_upcharge" ("upcharge_id") `);
        await queryRunner.query(`ALTER TABLE "hardware_set" ADD CONSTRAINT "FK_612cda76e543603b8c455788b5c" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "FK_59e520beb3bb0606a3a0c2dc797" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "markup" ADD CONSTRAINT "FK_1a272d4555dbc776202913fd828" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "finish" ADD CONSTRAINT "FK_0fa2e017dc40d7cbef34a68a072" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vendor" ADD CONSTRAINT "FK_08b4e8e5f359316005b0a97f3ee" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "model" ADD CONSTRAINT "FK_7722d0522cf52b10609ca0a725f" FOREIGN KEY ("material_type_id") REFERENCES "material_type"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material" ADD CONSTRAINT "FK_5a4135c8b2d9e33f55b25e78e21" FOREIGN KEY ("type_id") REFERENCES "material_type"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material" ADD CONSTRAINT "FK_35ac89da66b3cf49672570116cc" FOREIGN KEY ("vendor_id") REFERENCES "vendor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material" ADD CONSTRAINT "FK_5060f67c9340b62cb4f24a4d234" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profile" ADD CONSTRAINT "FK_a1c3871b2b1cac747daf8425e57" FOREIGN KEY ("vendor_id") REFERENCES "vendor"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profile" ADD CONSTRAINT "FK_a39874be76793f8a9be22dcf4df" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profile" ADD CONSTRAINT "FK_ac89e7d1d10e398109385a3deb0" FOREIGN KEY ("room_id") REFERENCES "room"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_430fe388f11ce6e52899829753c" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_6e5db90c5420780a7e496835e12" FOREIGN KEY ("exterior_openings_door_model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_a5f36516422369403218afac562" FOREIGN KEY ("exterior_openings_door_material_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_506fac0c08b3b2c8a64af04df9c" FOREIGN KEY ("exterior_openings_door_profile_set_edge_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_9b12d22c37988ea8b434887547a" FOREIGN KEY ("exterior_openings_door_profile_set_frame_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_fe845296869782e5f579e7d8725" FOREIGN KEY ("exterior_openings_door_profile_set_panel_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_bb1537f21e499f3292c38b6d94c" FOREIGN KEY ("exterior_openings_door_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_a59b361c9e3456ad921dfecb4ac" FOREIGN KEY ("exterior_openings_door_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_fde1b88d8bdc48cf76a17480332" FOREIGN KEY ("exterior_openings_door_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_166192d0169ed9e4cb951971a9a" FOREIGN KEY ("exterior_openings_drawer_model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_c08217b650215926043eba487a2" FOREIGN KEY ("exterior_openings_drawer_material_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_5849eec825a667271e35db334d9" FOREIGN KEY ("exterior_openings_drawer_profile_set_edge_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_759b694a1a4e651b1682e5fe935" FOREIGN KEY ("exterior_openings_drawer_profile_set_frame_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_2e02ad332a35f0806f8af3a7739" FOREIGN KEY ("exterior_openings_drawer_profile_set_panel_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_ab84a498eb003872bbf2f2d44b2" FOREIGN KEY ("exterior_openings_drawer_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_01e1a6748eda428868ac74eb491" FOREIGN KEY ("exterior_openings_drawer_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_2a914f21df45defc5dd18851cdc" FOREIGN KEY ("exterior_openings_drawer_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_7fe2e29dfeba1e7709b0b522404" FOREIGN KEY ("exterior_panels_appliance_model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_2871fd88cbf35c0fecd7cb219f5" FOREIGN KEY ("exterior_panels_appliance_material_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_7d58edbb71bb1c160629c843c70" FOREIGN KEY ("exterior_panels_appliance_profile_set_edge_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_fd2f12f841071f8516a1a3a640f" FOREIGN KEY ("exterior_panels_appliance_profile_set_frame_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_b3b564ae1fc31eb0f26d66a2427" FOREIGN KEY ("exterior_panels_appliance_profile_set_panel_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_41abdca07ab3fb5f89e0764eb14" FOREIGN KEY ("exterior_panels_appliance_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_94b32d4c6b60612f0a9a9ef60a9" FOREIGN KEY ("exterior_panels_appliance_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_8690013dc21e2ff475099f2cc0d" FOREIGN KEY ("exterior_panels_appliance_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_256e9b7f1aea28ce8617c3a098b" FOREIGN KEY ("exterior_panels_end_model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_b79139c2ce62174b8058250a214" FOREIGN KEY ("exterior_panels_end_material_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_9e8b866e37f99362ad893d34d09" FOREIGN KEY ("exterior_panels_end_profile_set_edge_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_a474016762dfda2a195e3eb4af4" FOREIGN KEY ("exterior_panels_end_profile_set_frame_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_f1b9341d22296705ffc184e6855" FOREIGN KEY ("exterior_panels_end_profile_set_panel_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_337c2f2f89d6654f59ba4b3e9d2" FOREIGN KEY ("exterior_panels_end_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_c42fb4df9321e8194bb62cc48f2" FOREIGN KEY ("exterior_panels_end_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_626b72d825242d1c4d50ca57d1c" FOREIGN KEY ("exterior_panels_end_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_42ec079b545efa043c83a416586" FOREIGN KEY ("exterior_panels_wainscot_model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_885292469c159b45e59793b3329" FOREIGN KEY ("exterior_panels_wainscot_material_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_71c431e83e41077d55cef12cfba" FOREIGN KEY ("exterior_panels_wainscot_profile_set_edge_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_e149e815b935a780276604e9e60" FOREIGN KEY ("exterior_panels_wainscot_profile_set_frame_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_66a56662fa11fa852f8b0940a98" FOREIGN KEY ("exterior_panels_wainscot_profile_set_panel_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_f76d23873169af1abf374a63f57" FOREIGN KEY ("exterior_panels_wainscot_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_0e2ea417d6505a1d0318e064535" FOREIGN KEY ("exterior_panels_wainscot_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_38e5bf4e3be8b749645be40adec" FOREIGN KEY ("exterior_panels_wainscot_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_c5f7d6f6f527d10163e379066f0" FOREIGN KEY ("exterior_panels_slab_model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_51383465852fd86c55d3b1aaa2d" FOREIGN KEY ("exterior_panels_slab_material_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_aed8b7936def3ca2499cc35d5df" FOREIGN KEY ("exterior_panels_slab_profile_set_edge_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_1f81872c25f87b327550a0fa528" FOREIGN KEY ("exterior_panels_slab_profile_set_frame_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_f050eb0a24b6c27b40f2df1c741" FOREIGN KEY ("exterior_panels_slab_profile_set_panel_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_30fbf1fdaebec044a194dd5f4dd" FOREIGN KEY ("exterior_panels_slab_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_78277b7719972341997f11362d4" FOREIGN KEY ("exterior_panels_slab_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_cbca317d30db27ce31b98fb947d" FOREIGN KEY ("exterior_panels_slab_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_057e0a34997080a6de4e76caa2a" FOREIGN KEY ("exterior_fillers_model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_92f7e7da81fc8fdf585537f07ad" FOREIGN KEY ("exterior_fillers_material_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_845d873c2838de4970bc882cee1" FOREIGN KEY ("exterior_fillers_profile_set_edge_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_f29b1e73c5e80e681277cc0496b" FOREIGN KEY ("exterior_fillers_profile_set_frame_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_456253f0e87f93e7c26c1f37724" FOREIGN KEY ("exterior_fillers_profile_set_panel_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_9285d0064ed1e7c92f96b47daf5" FOREIGN KEY ("exterior_fillers_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_b2627541f853478d27d34740758" FOREIGN KEY ("exterior_fillers_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_32f2612887a3764778a3943f49c" FOREIGN KEY ("exterior_fillers_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_a6da5109a9c210c3ad521a5f436" FOREIGN KEY ("exterior_toes_model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_6aed59e2914eac499ed87bd30a2" FOREIGN KEY ("exterior_toes_material_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_a37d95971262c43733c0ccc1b44" FOREIGN KEY ("exterior_toes_profile_set_edge_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_067cf68f80fa46b8683d06b969b" FOREIGN KEY ("exterior_toes_profile_set_frame_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_1606b5ad57afff838ae68edd3bd" FOREIGN KEY ("exterior_toes_profile_set_panel_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_03bb41502770824787d0c15ba3f" FOREIGN KEY ("exterior_toes_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_3dcdaa782cf92b6c32833d8e570" FOREIGN KEY ("exterior_toes_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_b767e2b4f53c68300a87917a35e" FOREIGN KEY ("exterior_toes_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_2624a7a03cb1153db3261776f65" FOREIGN KEY ("exterior_face_frame_model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_69145c4e6f35f4157cb097e0e1c" FOREIGN KEY ("exterior_face_frame_material_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_3677bac82997c10434b0859ade2" FOREIGN KEY ("exterior_face_frame_profile_set_edge_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_7a690ae6595a4c0951667953c74" FOREIGN KEY ("exterior_face_frame_profile_set_frame_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_7d022495d959dedcdf790cd666a" FOREIGN KEY ("exterior_face_frame_profile_set_panel_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_7379d50486d85ce81bfeac3a602" FOREIGN KEY ("exterior_face_frame_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_7a15c488411321b30f31f68427f" FOREIGN KEY ("exterior_face_frame_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_c35ce0ab346c1ba5b94d0e98017" FOREIGN KEY ("exterior_face_frame_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_5d66405046d4ab7286ab349c1a1" FOREIGN KEY ("exterior_edgebanding_model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_e237d639dda8fcd2336a2dd33cd" FOREIGN KEY ("exterior_edgebanding_material_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_64c144182f6c38fc6c74528fe2d" FOREIGN KEY ("exterior_edgebanding_profile_set_edge_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_b70cbf2752cb399df0060487d1e" FOREIGN KEY ("exterior_edgebanding_profile_set_frame_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_24e872ee53607be8ebcc3b6e623" FOREIGN KEY ("exterior_edgebanding_profile_set_panel_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_917e5305a8aed06ec747c36d002" FOREIGN KEY ("exterior_edgebanding_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_7e150d01c08fbaa79563b95962d" FOREIGN KEY ("exterior_edgebanding_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_e2c49fe5646eacaf3ca184a0a5a" FOREIGN KEY ("exterior_edgebanding_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_392ba5713e85cd021d12c3e7f99" FOREIGN KEY ("exterior_molding_crown_model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_545417288957fdfe03bb8892a06" FOREIGN KEY ("exterior_molding_crown_material_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_a696dcbc9b5cdff344a59bb1e10" FOREIGN KEY ("exterior_molding_crown_profile_set_edge_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_86efed3d20fa1fc94c2831d9cb3" FOREIGN KEY ("exterior_molding_crown_profile_set_frame_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_199a237bf844f52119ed613475a" FOREIGN KEY ("exterior_molding_crown_profile_set_panel_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_8def4c8ddd3731a706bc51dd349" FOREIGN KEY ("exterior_molding_crown_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_4fbf6a6e3c4544ddd549fd0ee85" FOREIGN KEY ("exterior_molding_crown_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_c89f6c927e262bb9181642a6a54" FOREIGN KEY ("exterior_molding_crown_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_c69e489766b2d7b9a6040134ca4" FOREIGN KEY ("exterior_molding_light_rail_model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_e1967a8bd36b85783a5dffd9c7a" FOREIGN KEY ("exterior_molding_light_rail_material_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_290f1bfc55b2465fb53f924b3be" FOREIGN KEY ("exterior_molding_light_rail_profile_set_edge_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_14535e1d0b34d3ce33081ab1885" FOREIGN KEY ("exterior_molding_light_rail_profile_set_frame_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_75480fe17d8cd24967299ee7378" FOREIGN KEY ("exterior_molding_light_rail_profile_set_panel_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_4cadb3528bec3bafb307c0be87c" FOREIGN KEY ("exterior_molding_light_rail_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_3c817245c60d545bd07b5003579" FOREIGN KEY ("exterior_molding_light_rail_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_67129f98db1b0c043a48aec5f90" FOREIGN KEY ("exterior_molding_light_rail_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_fcada5064e4cd24c4e42303b433" FOREIGN KEY ("interior_cabinets_unfinished_interior_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_81f06d5b21879b237fc4008cb90" FOREIGN KEY ("interior_cabinets_unfinished_back_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_3c3d18b21c7587cdc33d346c0bb" FOREIGN KEY ("interior_cabinets_unfinished_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_4047f97c1a04aeb8ae6bd939cbb" FOREIGN KEY ("interior_cabinets_unfinished_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_b590fad1d2cad047048f6d8a05c" FOREIGN KEY ("interior_cabinets_unfinished_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_fd536d98afe50222dc945698d62" FOREIGN KEY ("interior_cabinets_finished_interior_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_5fdcbcfac1eb32eeddbd60ac63c" FOREIGN KEY ("interior_cabinets_finished_back_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_bd2767d67b6d6c12479555b3747" FOREIGN KEY ("interior_cabinets_finished_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_40902d0bba37f519677e658d662" FOREIGN KEY ("interior_cabinets_finished_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_8b1a72086a6e6c9e38db4af0513" FOREIGN KEY ("interior_cabinets_finished_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_d8dc2827eec8a087ac1e00217e4" FOREIGN KEY ("interior_openings_box_model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_bdbe6ab55370a2f9c82f73c967b" FOREIGN KEY ("interior_openings_box_material_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_f2ce966a50c659f06663752908f" FOREIGN KEY ("interior_openings_box_profile_set_edge_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_9ca91150e6447bcb4856503f7a9" FOREIGN KEY ("interior_openings_box_profile_set_frame_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_98321b0988b8d9e6fbe8cbaf1b6" FOREIGN KEY ("interior_openings_box_profile_set_panel_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_e1ec6208560df27d2ad1833a5a5" FOREIGN KEY ("interior_openings_box_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_7cb0baf897911e3efdc2d880726" FOREIGN KEY ("interior_openings_box_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_7b37d6a54c1b20e98de625e9579" FOREIGN KEY ("interior_openings_box_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_a61c8b732762b3acf0c59a4d8ba" FOREIGN KEY ("interior_openings_tray_model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_682d269d059ddbc0169448adae0" FOREIGN KEY ("interior_openings_tray_material_id") REFERENCES "material"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_bc3d34e996e8c14a3444d2e8abd" FOREIGN KEY ("interior_openings_tray_profile_set_edge_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_49c3c4047f524fb8aa32f9e62bc" FOREIGN KEY ("interior_openings_tray_profile_set_frame_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_4b49cf94b1f9320b879b5f6e28e" FOREIGN KEY ("interior_openings_tray_profile_set_panel_id") REFERENCES "profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_5997b8225f74f0bc93e3c5dd3ba" FOREIGN KEY ("interior_openings_tray_finish_set_process_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_d610215adefb58e140f2722d301" FOREIGN KEY ("interior_openings_tray_finish_set_glaze_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "material_set" ADD CONSTRAINT "FK_16a47536d2513103d259dd0116e" FOREIGN KEY ("interior_openings_tray_finish_set_paint_id") REFERENCES "finish"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terms" ADD CONSTRAINT "FK_3e189248a5fe0d58c0bc986e2bd" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_preferences" ADD CONSTRAINT "FK_0ed0f9ad32368f747dc165fd6e5" FOREIGN KEY ("terms_id") REFERENCES "terms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_preferences" ADD CONSTRAINT "FK_9e5fadacba01d94d5d70bdbff58" FOREIGN KEY ("markup_id") REFERENCES "markup"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_preferences" ADD CONSTRAINT "FK_918dbdb11d27818f94fa949904b" FOREIGN KEY ("material_set_id") REFERENCES "material_set"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_preferences" ADD CONSTRAINT "FK_feca787023742c1c904fd7e09ab" FOREIGN KEY ("hardware_set_id") REFERENCES "hardware_set"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_preferences" ADD CONSTRAINT "FK_59349957f79fceda67b164f314e" FOREIGN KEY ("cabinet_specifications_id") REFERENCES "cabinet_specifications"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_preferences" ADD CONSTRAINT "FK_f889da5b713c033b5c89bf4ae81" FOREIGN KEY ("terms_id") REFERENCES "terms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_preferences" ADD CONSTRAINT "FK_35c1ef0b7eb43c32e41692330b0" FOREIGN KEY ("markup_id") REFERENCES "markup"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_preferences" ADD CONSTRAINT "FK_395a0e49c3273705a372e932e3f" FOREIGN KEY ("material_set_id") REFERENCES "material_set"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_preferences" ADD CONSTRAINT "FK_23fe4cdae841ca95b9f93c06249" FOREIGN KEY ("hardware_set_id") REFERENCES "hardware_set"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_preferences" ADD CONSTRAINT "FK_31ce49ae9dc0df14c7e8ec4233a" FOREIGN KEY ("cabinet_specifications_id") REFERENCES "cabinet_specifications"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_preferences" ADD CONSTRAINT "FK_5fe82dbb55cea8662c6b407dee6" FOREIGN KEY ("terms_id") REFERENCES "terms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_preferences" ADD CONSTRAINT "FK_2f44627ccda5bbc9eb480e5d01c" FOREIGN KEY ("markup_id") REFERENCES "markup"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_preferences" ADD CONSTRAINT "FK_7ffda0fd32d01179a3a88d1b26b" FOREIGN KEY ("material_set_id") REFERENCES "material_set"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_preferences" ADD CONSTRAINT "FK_533650eb0e2647f5e1a5dc34acb" FOREIGN KEY ("hardware_set_id") REFERENCES "hardware_set"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_preferences" ADD CONSTRAINT "FK_ac2afd4c17f457e16e8473aeec1" FOREIGN KEY ("cabinet_specifications_id") REFERENCES "cabinet_specifications"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client" ADD CONSTRAINT "FK_b3627c981b3d782cb5a2845e3d8" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client" ADD CONSTRAINT "FK_0d06e691326d586481f28447cfb" FOREIGN KEY ("preferences_id") REFERENCES "client_preferences"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client" ADD CONSTRAINT "FK_0b35eeade60c594a9b0b2a61b71" FOREIGN KEY ("addresses_mailing_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client" ADD CONSTRAINT "FK_487d70af2ae8a1d665b3c16c1ba" FOREIGN KEY ("addresses_physical_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_cc52bb1d22b93ebd7d86a88da4d" FOREIGN KEY ("client_id") REFERENCES "client"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_80174406bf48aa737052326682b" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_0fec48157a95b4d070dd1527244" FOREIGN KEY ("preferences_id") REFERENCES "job_preferences"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "upcharge" ADD CONSTRAINT "FK_8e416be8ebc087849371ce0f79f" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room" ADD CONSTRAINT "FK_12dd210e46c2e70825423706590" FOREIGN KEY ("material_set_id") REFERENCES "material_set"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room" ADD CONSTRAINT "FK_5413f589e26d684ee473be324bc" FOREIGN KEY ("hardware_set_id") REFERENCES "hardware_set"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room" ADD CONSTRAINT "FK_e9e53e5f10ed89175f977a72318" FOREIGN KEY ("job_id") REFERENCES "job"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room" ADD CONSTRAINT "FK_df465d35ac761ca1e7f79df1956" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "toe_platform" ADD CONSTRAINT "FK_6e7812e3700583caa59a708f909" FOREIGN KEY ("cabinet_id") REFERENCES "cabinet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "toe_platform" ADD CONSTRAINT "FK_677a2dc1723ce04ac92ec69d0a2" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "toe_platform" ADD CONSTRAINT "FK_afd5b98fe9128250e0f2e89451d" FOREIGN KEY ("room_id") REFERENCES "room"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "panel" ADD CONSTRAINT "FK_ad19449095d9bf65be1a3254b6d" FOREIGN KEY ("cabinet_id") REFERENCES "cabinet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "panel" ADD CONSTRAINT "FK_8ffed47dfa18261c4d88e9fc429" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "panel" ADD CONSTRAINT "FK_88097c43070cdbe7e3038631491" FOREIGN KEY ("room_id") REFERENCES "room"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "filler" ADD CONSTRAINT "FK_9698cc77823c8676e6cdfbeef5d" FOREIGN KEY ("cabinet_id") REFERENCES "cabinet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "filler" ADD CONSTRAINT "FK_de700ab22b2f9bca6bbdc554758" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "filler" ADD CONSTRAINT "FK_65be08a094dbdbe6f79b9745aa6" FOREIGN KEY ("room_id") REFERENCES "room"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opening" ADD CONSTRAINT "FK_2ab91dcc4c611b02f51dc9d9532" FOREIGN KEY ("model_id") REFERENCES "model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opening" ADD CONSTRAINT "FK_28ce6d24b5357e814d3cdf3701c" FOREIGN KEY ("vendor_id") REFERENCES "vendor"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opening" ADD CONSTRAINT "FK_b8e558c10557180991c50bea233" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opening" ADD CONSTRAINT "FK_61144682d1e3c4bb61d4e451f18" FOREIGN KEY ("room_id") REFERENCES "room"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opening" ADD CONSTRAINT "FK_a540a160d3057a4424184113ccf" FOREIGN KEY ("cabinet_id") REFERENCES "cabinet"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cabinet" ADD CONSTRAINT "FK_a23f521046585b5ee033fb4f5c9" FOREIGN KEY ("specifications_id") REFERENCES "cabinet_specifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cabinet" ADD CONSTRAINT "FK_4be0b1d4d96f55d481939c200d7" FOREIGN KEY ("room_id") REFERENCES "room"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cabinet" ADD CONSTRAINT "FK_2685c6bbfe87898c3e24f04f8c7" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account" ADD CONSTRAINT "FK_35f5ce85c1ef8f032df1311b452" FOREIGN KEY ("preferences_id") REFERENCES "account_preferences"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cabinet_equipment" ADD CONSTRAINT "FK_439b06d85cd537c8a47e32c15b6" FOREIGN KEY ("cabinet_id") REFERENCES "cabinet"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cabinet_equipment" ADD CONSTRAINT "FK_0b2f7ee831d3a159f5898497416" FOREIGN KEY ("room_id") REFERENCES "room"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cabinet_equipment" ADD CONSTRAINT "FK_6a90c36cdfb1ce892e70f2c3ce1" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "letter" ADD CONSTRAINT "FK_b5a278beb945f8dde037cbd2f24" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_upcharges_upcharge" ADD CONSTRAINT "FK_99706143f4e3444e570910a651a" FOREIGN KEY ("room_id") REFERENCES "room"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "room_upcharges_upcharge" ADD CONSTRAINT "FK_7a614a4aab6d53ba2025766ab9b" FOREIGN KEY ("upcharge_id") REFERENCES "upcharge"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cabinet_upcharges_upcharge" ADD CONSTRAINT "FK_de9c5d240a47f96f784647580be" FOREIGN KEY ("cabinet_id") REFERENCES "cabinet"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cabinet_upcharges_upcharge" ADD CONSTRAINT "FK_c6a90bec44895e1441d3343e83c" FOREIGN KEY ("upcharge_id") REFERENCES "upcharge"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cabinet_equipment_upcharges_upcharge" ADD CONSTRAINT "FK_87f2db6158854538d56ac1218b5" FOREIGN KEY ("cabinet_equipment_id") REFERENCES "cabinet_equipment"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cabinet_equipment_upcharges_upcharge" ADD CONSTRAINT "FK_12baf7572789a196ce6fa88dbcc" FOREIGN KEY ("upcharge_id") REFERENCES "upcharge"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cabinet_equipment_upcharges_upcharge" DROP CONSTRAINT "FK_12baf7572789a196ce6fa88dbcc"`);
        await queryRunner.query(`ALTER TABLE "cabinet_equipment_upcharges_upcharge" DROP CONSTRAINT "FK_87f2db6158854538d56ac1218b5"`);
        await queryRunner.query(`ALTER TABLE "cabinet_upcharges_upcharge" DROP CONSTRAINT "FK_c6a90bec44895e1441d3343e83c"`);
        await queryRunner.query(`ALTER TABLE "cabinet_upcharges_upcharge" DROP CONSTRAINT "FK_de9c5d240a47f96f784647580be"`);
        await queryRunner.query(`ALTER TABLE "room_upcharges_upcharge" DROP CONSTRAINT "FK_7a614a4aab6d53ba2025766ab9b"`);
        await queryRunner.query(`ALTER TABLE "room_upcharges_upcharge" DROP CONSTRAINT "FK_99706143f4e3444e570910a651a"`);
        await queryRunner.query(`ALTER TABLE "letter" DROP CONSTRAINT "FK_b5a278beb945f8dde037cbd2f24"`);
        await queryRunner.query(`ALTER TABLE "cabinet_equipment" DROP CONSTRAINT "FK_6a90c36cdfb1ce892e70f2c3ce1"`);
        await queryRunner.query(`ALTER TABLE "cabinet_equipment" DROP CONSTRAINT "FK_0b2f7ee831d3a159f5898497416"`);
        await queryRunner.query(`ALTER TABLE "cabinet_equipment" DROP CONSTRAINT "FK_439b06d85cd537c8a47e32c15b6"`);
        await queryRunner.query(`ALTER TABLE "account" DROP CONSTRAINT "FK_35f5ce85c1ef8f032df1311b452"`);
        await queryRunner.query(`ALTER TABLE "cabinet" DROP CONSTRAINT "FK_2685c6bbfe87898c3e24f04f8c7"`);
        await queryRunner.query(`ALTER TABLE "cabinet" DROP CONSTRAINT "FK_4be0b1d4d96f55d481939c200d7"`);
        await queryRunner.query(`ALTER TABLE "cabinet" DROP CONSTRAINT "FK_a23f521046585b5ee033fb4f5c9"`);
        await queryRunner.query(`ALTER TABLE "opening" DROP CONSTRAINT "FK_a540a160d3057a4424184113ccf"`);
        await queryRunner.query(`ALTER TABLE "opening" DROP CONSTRAINT "FK_61144682d1e3c4bb61d4e451f18"`);
        await queryRunner.query(`ALTER TABLE "opening" DROP CONSTRAINT "FK_b8e558c10557180991c50bea233"`);
        await queryRunner.query(`ALTER TABLE "opening" DROP CONSTRAINT "FK_28ce6d24b5357e814d3cdf3701c"`);
        await queryRunner.query(`ALTER TABLE "opening" DROP CONSTRAINT "FK_2ab91dcc4c611b02f51dc9d9532"`);
        await queryRunner.query(`ALTER TABLE "filler" DROP CONSTRAINT "FK_65be08a094dbdbe6f79b9745aa6"`);
        await queryRunner.query(`ALTER TABLE "filler" DROP CONSTRAINT "FK_de700ab22b2f9bca6bbdc554758"`);
        await queryRunner.query(`ALTER TABLE "filler" DROP CONSTRAINT "FK_9698cc77823c8676e6cdfbeef5d"`);
        await queryRunner.query(`ALTER TABLE "panel" DROP CONSTRAINT "FK_88097c43070cdbe7e3038631491"`);
        await queryRunner.query(`ALTER TABLE "panel" DROP CONSTRAINT "FK_8ffed47dfa18261c4d88e9fc429"`);
        await queryRunner.query(`ALTER TABLE "panel" DROP CONSTRAINT "FK_ad19449095d9bf65be1a3254b6d"`);
        await queryRunner.query(`ALTER TABLE "toe_platform" DROP CONSTRAINT "FK_afd5b98fe9128250e0f2e89451d"`);
        await queryRunner.query(`ALTER TABLE "toe_platform" DROP CONSTRAINT "FK_677a2dc1723ce04ac92ec69d0a2"`);
        await queryRunner.query(`ALTER TABLE "toe_platform" DROP CONSTRAINT "FK_6e7812e3700583caa59a708f909"`);
        await queryRunner.query(`ALTER TABLE "room" DROP CONSTRAINT "FK_df465d35ac761ca1e7f79df1956"`);
        await queryRunner.query(`ALTER TABLE "room" DROP CONSTRAINT "FK_e9e53e5f10ed89175f977a72318"`);
        await queryRunner.query(`ALTER TABLE "room" DROP CONSTRAINT "FK_5413f589e26d684ee473be324bc"`);
        await queryRunner.query(`ALTER TABLE "room" DROP CONSTRAINT "FK_12dd210e46c2e70825423706590"`);
        await queryRunner.query(`ALTER TABLE "upcharge" DROP CONSTRAINT "FK_8e416be8ebc087849371ce0f79f"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_0fec48157a95b4d070dd1527244"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_80174406bf48aa737052326682b"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_cc52bb1d22b93ebd7d86a88da4d"`);
        await queryRunner.query(`ALTER TABLE "client" DROP CONSTRAINT "FK_487d70af2ae8a1d665b3c16c1ba"`);
        await queryRunner.query(`ALTER TABLE "client" DROP CONSTRAINT "FK_0b35eeade60c594a9b0b2a61b71"`);
        await queryRunner.query(`ALTER TABLE "client" DROP CONSTRAINT "FK_0d06e691326d586481f28447cfb"`);
        await queryRunner.query(`ALTER TABLE "client" DROP CONSTRAINT "FK_b3627c981b3d782cb5a2845e3d8"`);
        await queryRunner.query(`ALTER TABLE "job_preferences" DROP CONSTRAINT "FK_ac2afd4c17f457e16e8473aeec1"`);
        await queryRunner.query(`ALTER TABLE "job_preferences" DROP CONSTRAINT "FK_533650eb0e2647f5e1a5dc34acb"`);
        await queryRunner.query(`ALTER TABLE "job_preferences" DROP CONSTRAINT "FK_7ffda0fd32d01179a3a88d1b26b"`);
        await queryRunner.query(`ALTER TABLE "job_preferences" DROP CONSTRAINT "FK_2f44627ccda5bbc9eb480e5d01c"`);
        await queryRunner.query(`ALTER TABLE "job_preferences" DROP CONSTRAINT "FK_5fe82dbb55cea8662c6b407dee6"`);
        await queryRunner.query(`ALTER TABLE "client_preferences" DROP CONSTRAINT "FK_31ce49ae9dc0df14c7e8ec4233a"`);
        await queryRunner.query(`ALTER TABLE "client_preferences" DROP CONSTRAINT "FK_23fe4cdae841ca95b9f93c06249"`);
        await queryRunner.query(`ALTER TABLE "client_preferences" DROP CONSTRAINT "FK_395a0e49c3273705a372e932e3f"`);
        await queryRunner.query(`ALTER TABLE "client_preferences" DROP CONSTRAINT "FK_35c1ef0b7eb43c32e41692330b0"`);
        await queryRunner.query(`ALTER TABLE "client_preferences" DROP CONSTRAINT "FK_f889da5b713c033b5c89bf4ae81"`);
        await queryRunner.query(`ALTER TABLE "account_preferences" DROP CONSTRAINT "FK_59349957f79fceda67b164f314e"`);
        await queryRunner.query(`ALTER TABLE "account_preferences" DROP CONSTRAINT "FK_feca787023742c1c904fd7e09ab"`);
        await queryRunner.query(`ALTER TABLE "account_preferences" DROP CONSTRAINT "FK_918dbdb11d27818f94fa949904b"`);
        await queryRunner.query(`ALTER TABLE "account_preferences" DROP CONSTRAINT "FK_9e5fadacba01d94d5d70bdbff58"`);
        await queryRunner.query(`ALTER TABLE "account_preferences" DROP CONSTRAINT "FK_0ed0f9ad32368f747dc165fd6e5"`);
        await queryRunner.query(`ALTER TABLE "terms" DROP CONSTRAINT "FK_3e189248a5fe0d58c0bc986e2bd"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_16a47536d2513103d259dd0116e"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_d610215adefb58e140f2722d301"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_5997b8225f74f0bc93e3c5dd3ba"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_4b49cf94b1f9320b879b5f6e28e"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_49c3c4047f524fb8aa32f9e62bc"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_bc3d34e996e8c14a3444d2e8abd"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_682d269d059ddbc0169448adae0"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_a61c8b732762b3acf0c59a4d8ba"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_7b37d6a54c1b20e98de625e9579"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_7cb0baf897911e3efdc2d880726"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_e1ec6208560df27d2ad1833a5a5"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_98321b0988b8d9e6fbe8cbaf1b6"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_9ca91150e6447bcb4856503f7a9"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_f2ce966a50c659f06663752908f"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_bdbe6ab55370a2f9c82f73c967b"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_d8dc2827eec8a087ac1e00217e4"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_8b1a72086a6e6c9e38db4af0513"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_40902d0bba37f519677e658d662"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_bd2767d67b6d6c12479555b3747"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_5fdcbcfac1eb32eeddbd60ac63c"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_fd536d98afe50222dc945698d62"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_b590fad1d2cad047048f6d8a05c"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_4047f97c1a04aeb8ae6bd939cbb"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_3c3d18b21c7587cdc33d346c0bb"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_81f06d5b21879b237fc4008cb90"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_fcada5064e4cd24c4e42303b433"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_67129f98db1b0c043a48aec5f90"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_3c817245c60d545bd07b5003579"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_4cadb3528bec3bafb307c0be87c"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_75480fe17d8cd24967299ee7378"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_14535e1d0b34d3ce33081ab1885"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_290f1bfc55b2465fb53f924b3be"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_e1967a8bd36b85783a5dffd9c7a"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_c69e489766b2d7b9a6040134ca4"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_c89f6c927e262bb9181642a6a54"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_4fbf6a6e3c4544ddd549fd0ee85"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_8def4c8ddd3731a706bc51dd349"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_199a237bf844f52119ed613475a"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_86efed3d20fa1fc94c2831d9cb3"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_a696dcbc9b5cdff344a59bb1e10"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_545417288957fdfe03bb8892a06"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_392ba5713e85cd021d12c3e7f99"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_e2c49fe5646eacaf3ca184a0a5a"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_7e150d01c08fbaa79563b95962d"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_917e5305a8aed06ec747c36d002"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_24e872ee53607be8ebcc3b6e623"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_b70cbf2752cb399df0060487d1e"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_64c144182f6c38fc6c74528fe2d"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_e237d639dda8fcd2336a2dd33cd"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_5d66405046d4ab7286ab349c1a1"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_c35ce0ab346c1ba5b94d0e98017"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_7a15c488411321b30f31f68427f"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_7379d50486d85ce81bfeac3a602"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_7d022495d959dedcdf790cd666a"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_7a690ae6595a4c0951667953c74"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_3677bac82997c10434b0859ade2"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_69145c4e6f35f4157cb097e0e1c"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_2624a7a03cb1153db3261776f65"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_b767e2b4f53c68300a87917a35e"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_3dcdaa782cf92b6c32833d8e570"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_03bb41502770824787d0c15ba3f"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_1606b5ad57afff838ae68edd3bd"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_067cf68f80fa46b8683d06b969b"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_a37d95971262c43733c0ccc1b44"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_6aed59e2914eac499ed87bd30a2"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_a6da5109a9c210c3ad521a5f436"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_32f2612887a3764778a3943f49c"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_b2627541f853478d27d34740758"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_9285d0064ed1e7c92f96b47daf5"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_456253f0e87f93e7c26c1f37724"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_f29b1e73c5e80e681277cc0496b"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_845d873c2838de4970bc882cee1"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_92f7e7da81fc8fdf585537f07ad"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_057e0a34997080a6de4e76caa2a"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_cbca317d30db27ce31b98fb947d"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_78277b7719972341997f11362d4"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_30fbf1fdaebec044a194dd5f4dd"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_f050eb0a24b6c27b40f2df1c741"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_1f81872c25f87b327550a0fa528"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_aed8b7936def3ca2499cc35d5df"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_51383465852fd86c55d3b1aaa2d"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_c5f7d6f6f527d10163e379066f0"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_38e5bf4e3be8b749645be40adec"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_0e2ea417d6505a1d0318e064535"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_f76d23873169af1abf374a63f57"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_66a56662fa11fa852f8b0940a98"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_e149e815b935a780276604e9e60"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_71c431e83e41077d55cef12cfba"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_885292469c159b45e59793b3329"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_42ec079b545efa043c83a416586"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_626b72d825242d1c4d50ca57d1c"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_c42fb4df9321e8194bb62cc48f2"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_337c2f2f89d6654f59ba4b3e9d2"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_f1b9341d22296705ffc184e6855"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_a474016762dfda2a195e3eb4af4"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_9e8b866e37f99362ad893d34d09"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_b79139c2ce62174b8058250a214"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_256e9b7f1aea28ce8617c3a098b"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_8690013dc21e2ff475099f2cc0d"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_94b32d4c6b60612f0a9a9ef60a9"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_41abdca07ab3fb5f89e0764eb14"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_b3b564ae1fc31eb0f26d66a2427"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_fd2f12f841071f8516a1a3a640f"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_7d58edbb71bb1c160629c843c70"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_2871fd88cbf35c0fecd7cb219f5"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_7fe2e29dfeba1e7709b0b522404"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_2a914f21df45defc5dd18851cdc"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_01e1a6748eda428868ac74eb491"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_ab84a498eb003872bbf2f2d44b2"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_2e02ad332a35f0806f8af3a7739"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_759b694a1a4e651b1682e5fe935"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_5849eec825a667271e35db334d9"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_c08217b650215926043eba487a2"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_166192d0169ed9e4cb951971a9a"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_fde1b88d8bdc48cf76a17480332"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_a59b361c9e3456ad921dfecb4ac"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_bb1537f21e499f3292c38b6d94c"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_fe845296869782e5f579e7d8725"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_9b12d22c37988ea8b434887547a"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_506fac0c08b3b2c8a64af04df9c"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_a5f36516422369403218afac562"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_6e5db90c5420780a7e496835e12"`);
        await queryRunner.query(`ALTER TABLE "material_set" DROP CONSTRAINT "FK_430fe388f11ce6e52899829753c"`);
        await queryRunner.query(`ALTER TABLE "profile" DROP CONSTRAINT "FK_ac89e7d1d10e398109385a3deb0"`);
        await queryRunner.query(`ALTER TABLE "profile" DROP CONSTRAINT "FK_a39874be76793f8a9be22dcf4df"`);
        await queryRunner.query(`ALTER TABLE "profile" DROP CONSTRAINT "FK_a1c3871b2b1cac747daf8425e57"`);
        await queryRunner.query(`ALTER TABLE "material" DROP CONSTRAINT "FK_5060f67c9340b62cb4f24a4d234"`);
        await queryRunner.query(`ALTER TABLE "material" DROP CONSTRAINT "FK_35ac89da66b3cf49672570116cc"`);
        await queryRunner.query(`ALTER TABLE "material" DROP CONSTRAINT "FK_5a4135c8b2d9e33f55b25e78e21"`);
        await queryRunner.query(`ALTER TABLE "model" DROP CONSTRAINT "FK_7722d0522cf52b10609ca0a725f"`);
        await queryRunner.query(`ALTER TABLE "vendor" DROP CONSTRAINT "FK_08b4e8e5f359316005b0a97f3ee"`);
        await queryRunner.query(`ALTER TABLE "finish" DROP CONSTRAINT "FK_0fa2e017dc40d7cbef34a68a072"`);
        await queryRunner.query(`ALTER TABLE "markup" DROP CONSTRAINT "FK_1a272d4555dbc776202913fd828"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "FK_59e520beb3bb0606a3a0c2dc797"`);
        await queryRunner.query(`ALTER TABLE "hardware_set" DROP CONSTRAINT "FK_612cda76e543603b8c455788b5c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12baf7572789a196ce6fa88dbc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87f2db6158854538d56ac1218b"`);
        await queryRunner.query(`DROP TABLE "cabinet_equipment_upcharges_upcharge"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6a90bec44895e1441d3343e83"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de9c5d240a47f96f784647580b"`);
        await queryRunner.query(`DROP TABLE "cabinet_upcharges_upcharge"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a614a4aab6d53ba2025766ab9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99706143f4e3444e570910a651"`);
        await queryRunner.query(`DROP TABLE "room_upcharges_upcharge"`);
        await queryRunner.query(`DROP TABLE "letter"`);
        await queryRunner.query(`DROP TABLE "cabinet_equipment"`);
        await queryRunner.query(`DROP TABLE "account"`);
        await queryRunner.query(`DROP TABLE "cabinet"`);
        await queryRunner.query(`DROP TABLE "opening"`);
        await queryRunner.query(`DROP TABLE "filler"`);
        await queryRunner.query(`DROP TABLE "panel"`);
        await queryRunner.query(`DROP TABLE "toe_platform"`);
        await queryRunner.query(`DROP TABLE "room"`);
        await queryRunner.query(`DROP TABLE "upcharge"`);
        await queryRunner.query(`DROP TABLE "job"`);
        await queryRunner.query(`DROP TABLE "client"`);
        await queryRunner.query(`DROP TABLE "job_preferences"`);
        await queryRunner.query(`DROP TABLE "client_preferences"`);
        await queryRunner.query(`DROP TABLE "account_preferences"`);
        await queryRunner.query(`DROP TABLE "terms"`);
        await queryRunner.query(`DROP TABLE "material_set"`);
        await queryRunner.query(`DROP TABLE "profile"`);
        await queryRunner.query(`DROP TABLE "material"`);
        await queryRunner.query(`DROP TABLE "model"`);
        await queryRunner.query(`DROP TABLE "material_type"`);
        await queryRunner.query(`DROP TABLE "vendor"`);
        await queryRunner.query(`DROP TABLE "finish"`);
        await queryRunner.query(`DROP TABLE "markup"`);
        await queryRunner.query(`DROP TABLE "cabinet_specifications"`);
        await queryRunner.query(`DROP TABLE "address"`);
        await queryRunner.query(`DROP TABLE "hardware_set"`);
    }

}
