import { Account } from "./account";
export interface SpecificationRoot {
  id: string;
  is_default: boolean;
  image_url: string;
  name: string;
  back_position_method: string;
  back_thickness: number;
  dado_depth: number;
  rabbet_width: number;
  corner_back_vertical_diagonal_width: number;
  face_frame_rail_height: number;
  top_rail_number_of_finish_sides: number;
  center_rail_number_of_finish_sides_one: number;
  center_rail_number_of_finish_sides_two: number;
  center_rail_number_of_finish_sides_three: number;
  center_rail_number_of_finish_sides_four: number;
  bottom_rail_number_of_finish_sides: number;
  face_frame_stile_width: number;
  stile_number_of_finish_sides: number;
  drawer_door_allowance: number;
  drawer_depth_difference: number;
  door_drawer_reveal: number;
  filler_standard_width: number;
  finished_ends: number;
  number_of_finished_ends: number;
  cabinet_material_thickness: number;
  shelf_with_clearance: number;
  toe_kick_height: number;
  toe_kick_depth: number;
  account: Account;
  created_at: Date;
  updated_at: Date;
}
interface ICabinetPart {
  cabinet_height: number;
  cabinet_depth: number;
  floor_to_bottom_of_upper: number;
  include_top: boolean;
  number_of_top_finished_sides: number;
  depth_difference_top: number;
  top_depth: number;
  include_back: boolean;
  number_of_back_finished_sides: number;
  depth_top_back_stretcher: number;
  number_of_top_back_stretcher_finished_sides: number;
  nailer_height: number;
  nailer_quantity: number;
  number_of_nailer_finished_sides: number;
  subtract_nailer_from_back: number;
  depth_top_front_stretcher: number;
  number_of_top_front_stretcher_finished_sides: number;
  depth_stretcher_below_drawer: number;
  number_of_stretcher_below_drawer_finished_sides: number;
  number_of_adjusted_shelves: number;
  number_of_adjusted_shelves_finished_sides: number;
  depth_difference_adjusted_shelves: number;
  number_of_fixed_shelves: number;
  number_of_fixed_shelves_finished_sides: number;
  depth_difference_fixed_shelves: number;
  include_deck: boolean;
  number_of_deck_finished_sides: number;
  depth_difference_deck: number;
  number_of_cabinet_sides: number;
  number_of_cabinet_finished_sides: number;
}
export interface CabinetSpecification extends SpecificationRoot {
  base: ICabinetPart;
  vanity: ICabinetPart;
  tall: ICabinetPart;
  upper: ICabinetPart;
}
